dependencies:
- name: cloud-test-10
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: cloud-test-11
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: cloud-test-9
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: svc3
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
